Feature/api name enhancements
SFDO-Community/declarative-lookup-rollup-summaries pull request #1288
Opened 2022-12-10 02:33 UTC by ezralafleur

# Critical Changes

# Changes
- Renames inputs as suggested (Name -> Label, Unique Name -> API Name)
- Adds maxlength=40 to both inputs
- Uses Javascript to autofill an API name based on user's label input + regex matching API naming requirements

# Issues Closed
Resolves #1236

2023-01-22 11:03 UTC, Szandor72 requested changes
Thanks for picking this up and your patience. There are two topics to fix - Security Review Related Best Practices and more expressive/improved Regex. 

I can't find out why the builds aren't being marked as green, so hopefull the next commit will address this as well.

2023-01-22 11:03 UTC, Szandor72 commented on dlrs/main/pages/managelookuprollupsummaries_New.page
> +                                <apex:inputText onfocus="suggestApiName('{!$Component.labelInputSection.labelInput}', '{!$Component.nameInput}')" size="32" maxlength="40" id="nameInput" value="{!Look
Please use [`JSINHTMLENCODE()`](https://help.salesforce.com/s/articleView?id=sf.customize_functions_jsinhtmlencode.htm&type=5) for `suggestApiName('{!$Component.labelInputSection.labelInput}', '{!$Component.nameInput}'`. 
Security Review will otherwise flag this issue.

2023-01-22 11:03 UTC, Szandor72 commented on dlrs/main/pages/managelookuprollupsummaries_New.page
> +                                        name = label.trim();
`name` is not declared, neither as `var` nor via `let`; Did I miss something?

2023-01-22 11:03 UTC, Szandor72 commented on dlrs/main/pages/managelookuprollupsummaries_New.page
> +                                        name = [...name.matchAll(/[a-zA-Z0-9_]/g)].join('');
While regex are helpful, they are hard to read/edit. Please consider variablenames for the patterns (e.g. `var OneOrMoreSpacesPattern = / +/g`) and add documentation to the convertLabel function  
By using `OneOrMoreSpacesPattern`, you can avoid using line 87.

line 88 is removing special chars, right? line 89 escapes me -.-

Let's try to be more expressive, please.

2023-02-16 18:40 UTC, sfenton3 approved these changes

2023-02-18 08:35 UTC, Szandor72 approved these changes

2023-02-18 08:36 UTC, merged